services:
  web:
    build:
      context: .
      args:
        UV_SYNC_DEV_OPTION: ""
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    ports:
      - "8000:8000"
    volumes:
      - ./chile:/app/chile
