# Generated by Django 6.0.4 on 2026-04-19 03:10

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('Restaurant', 'Restaurant'), ('School / District', 'School'), ('Grocery / Co-op', 'Grocery'), ('Food Bank', 'Bank'), ('Other', 'Other')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('county', models.TextField(blank=True, null=True)),
                ('ped_grant_participant', models.BooleanField(default=False)),
                ('institution_type', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('geocode_source', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buyers',
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Herbs', 'Herbs'), ('Legumes', 'Legumes'), ('Livestock / Dairy', 'Livestock')], max_length=50)),
                ('season', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crops',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('owner_name', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('county', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('certifications', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('nm_grown_asp_approved', models.BooleanField(default=False)),
                ('asp_vendor_id', models.TextField(blank=True, null=True)),
                ('asp_approved_since', models.DateField(blank=True, null=True)),
                ('asp_counties_served', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True)),
                ('zip', models.TextField(blank=True, null=True)),
                ('products_offered', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True)),
                ('vendor_type', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('geocode_source', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'farms',
            },
        ),
        migrations.CreateModel(
            name='NMCounty',
            fields=[
                ('county_name', models.TextField(primary_key=True, serialize=False)),
                ('county_seat', models.TextField()),
                ('region', models.TextField()),
                ('population_2020', models.IntegerField(blank=True, null=True)),
                ('area_sq_miles', models.IntegerField(blank=True, null=True)),
                ('centroid_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centroid_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rural_urban_class', models.TextField(blank=True, null=True)),
                ('food_insecurity_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('child_food_insecurity_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('free_reduced_lunch_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pct_hispanic', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pct_native_american', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_farms_usda', models.IntegerField(blank=True, null=True)),
                ('num_school_districts', models.IntegerField(blank=True, null=True)),
                ('data_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nm_counties',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.TextField()),
                ('variety', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Herbs', 'Herbs'), ('Legumes', 'Legumes'), ('Livestock / Dairy', 'Livestock')], max_length=50)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_unit', models.CharField(choices=[('lbs', 'Lbs'), ('kg', 'Kg'), ('cases', 'Cases'), ('flats', 'Flats'), ('units', 'Units'), ('each', 'Each'), ('bushels', 'Bushels')], max_length=50)),
                ('min_order_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certifications', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True)),
                ('harvest_timestamp', models.DateTimeField(blank=True, null=True)),
                ('availability_start', models.DateField()),
                ('availability_end', models.DateField()),
                ('ped_eligible', models.BooleanField(default=False)),
                ('ped_eligible_items', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expiring', 'Expiring'), ('Sold Out', 'Sold Out'), ('Paused', 'Paused')], default='Active', max_length=50)),
                ('scratch_cooking_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='chile.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='chile.farm')),
            ],
            options={
                'db_table': 'listings',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Fulfilled', 'Fulfilled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('requested_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='chile.buyer')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='chile.listing')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
    ]
